robot_name: "small_hauler_2"
# imu_topic_name : "/hauler_1/imu"
cloud_topic_name: "/small_hauler_2/cloud"
#sensor_control_topic_name: "/hauler_1/sensor_controller/command"
sensor_pitch_control_topic_name: "/small_hauler_2/sensor/pitch/command/position"
sensor_yaw_control_topic_name: "/small_hauler_2/sensor/yaw/command/position"
