robot_name: "small_scout_1"
# imu_topic_name : "/scout_1/imu"
cloud_topic_name: "/small_scout_1/cloud"
sensor_pitch_control_topic_name: "/small_scout_1/sensor/pitch/command/position"
sensor_yaw_control_topic_name: "/small_scout_1/sensor/yaw/command/position"
